### ISSUE TITLE
Technology choices - Program Arduino/Raspberry Pi to communicate

### ISSUE THREAD

**Issue by maazsirkhot** [SJSUFall2019-CMPE272/Smart-Meter#2]
Hi Team,

I couldn't find concrete technological stack for passing the data to Arduino controller and making it communicate the results with each smart meter. Arduino controllers come in large varieties and each has their own pros and cons. It is critical what Arduino controller you choose for your solution. Furthermore, programming such a device would require hardware skills. Arduinos are very tricky and programming its behavior also requires C and core operating system designing skills. In summary, some background of Embedded systems would come handy to build this IOT device. I would suggest more exploration and planning in terms of implementation of hardware should be done well in advance.

Thank you!

**Comment by sarthakjain27** [comment]
Implementing hardware is our last priority. I believe it is mentioned in the readme too, that if only, we are successfully able to develop an application and we have time, we would go for implementing the hardware.
