### ISSUE TITLE
Business value - Is rescheduling a backward step?

### ISSUE THREAD

**Issue by maazsirkhot** [SJSUFall2019-CMPE272/Smart-Meter#3]
Hi Team,

I believe in today's age, electricity is a resource which cannot be checked. Limiting the supply of electricity at any given time or even forcing people to reschedule their activities is a backward step. As a consumer, I would not want meager incentives in return for not being able to use electricity the way I can. With more and more push towards electric usage in the automobile industry, usage of electricity cannot be compromised at any given time whether peak hour or not. However, to manage the excess load during peak hours, your solution can aim at producing and offering solar energy in complement to electricity. The model would aim to find the right balance between allocation of electricity in the form of traditional power and solar power. The proposed model will identify the peak periods and demands of electricity and likewise smoothly switch between solar and traditional power. Such a solution not only helps in reducing load on power plants but also promotes solar energy by enhancing its potential use. There are various research papers written on offering solar energy to complement traditional electricity and not replace traditional electricity. This is also more consumer friendly and thus more likely to be adopted on large scale.

Thank you!

**Comment by sarthakjain27** [comment]
I believe what you pointed out is correct. We could potentially integrate solar energy and add some batteries to store the renewable source of energy and use it. What I worry about is the real-time possibility of this aspect. This load scheduling field is pursued by researchers but no concrete application/product is out there in the market that could integrate solar panels with the grid to provide with a SMART SCHEDULE which is what we are aiming for in the project.
